#!/usr/bin/python3
import rclpy, numpy as np
from rclpy.node import Node
from rclpy.context import Context
from visualization_msgs.msg import Marker
from geometry_msgs.msg import Point
from nav_msgs.msg import OccupancyGrid
 

def main():
    proc= TiledRosProcess()
    proc.run()

class TiledRosProcess():
    # Constructor:
    def __init__(self):
        self._rosLocalNode= None

    def initializeRosNodes(self, ):
        #
        self._name= socket.gethostname()
        rosName= self._name.replace("-", "_")

    # ros callback
    def routine(self):
        print("Ba-Boum...")
        
    def incommingMap(self, mapMsg, reccord= True):
        # Reading the data
        width= mapMsg.info.width
        height= mapMsg.info.height
        resolution= round(mapMsg.info.resolution, 4)
        position= mapMsg.info.origin.position
        if round(position.z, 8) != 0.0 :
            self._rosLocalNode.get_logger().info(f"not coherent Z translation : {position.z}")
        px, py= position.x, position.y
        rotate= mapMsg.info.origin.orientation
        if round(rotate.x, 8) != 0.0 or round(rotate.y, 8) != 0.0 : 
            self._rosLocalNode.get_logger().info(f"not coherent X or Y rotation : {rotate.x, rotate.y}")
        if round(rotate.z, 8) != 0.0 : 
            self._rosLocalNode.get_logger().info(f"Rotation in Z not taked into account... : {rotate.z}")
        
        grid= np.array(mapMsg.data, dtype=np.int8).reshape((height, width))
        # Optionally map values to convenient representation (-1: unknow 0: free 100: obstacle)
        # Here keep original values but convert to signed ints
        self.grid = grid.copy()
        self.info = mapMsg.info
        
        self._rosLocalNode.get_logger().info( f"map: {width}x{height} at {resolution} on {px, py}\n" )
        if reccord :
            maplog= open( "incoming-map.log", "w" )
            maplog.write( f"map: {width}x{height} at {resolution} on {px, py}\n" )
            for line in grid :
                maplog.write( " ".join( [str(x) for x in line] )+ "\n" )
            maplog.close()

        poly= Marker()
        poly.header.frame_id= "map"
        poly.header.stamp= self._rosLocalNode.get_clock().now().to_msg()
        poly.ns = "tiledmap";
        poly.id= 1
        poly.type= Marker.LINE_STRIP
        poly.scale.x = 0.1
        
        poly.color.b = 1.0
        poly.color.a = 1.0

        for x, y in [(-1, -3), (1, -3), (1, 1), (-1, 1), (-1, -3)] :
            p= Point()
            p.x, p.y, p.z=  float(x), float(y), 0.0
            poly.points.append(p)
        self._poly_pub.publish(poly)

    # infinite loop
    def run(self):
        # Ros initialization
        rclpy.init()

        # local node :
        contextLocal = Context()
        contextLocal.init()
        self._rosLocalNode = Node( f"tiled_map_subscriber", context=contextLocal )

        # Multi node :
        # contextMulti = Context()
        # contextMulti.init(domain_id= 140)
        # self._rosNodeMulti = Node( f"parasit_{ rosName }", context=contextMulti )

        # Events handling :
        # self._tilemap_markers_pub= self._rosLocalNode.create_publisher( Pulse, 'tiledmap_markers', 10 )

        # Events handling :
        self._poly_pub= self._rosLocalNode.create_publisher( Marker, 'tiledmap', 10 )
        self._rosLocalNode.create_subscription( OccupancyGrid, "map", self.incommingMap, 10 )
        self._rosLocalNode.create_timer( 1.2, self.routine )

        # Infinite loop:
        executor= rclpy.get_global_executor()
        executor.add_node( self._rosLocalNode )
        #executor.add_node( self._rosNodeMulti )
        executor.spin()

        # Clean stop:
        self._rosLocalNode.destroy_node()
        #self._rosNodeMulti.destroy_node()


if __name__ == '__main__':
    main()