#!/usr/bin/python3
import rclpy, numpy as np, tiledland as tll
from rclpy.node import Node
from rclpy.context import Context
from visualization_msgs.msg import Marker
from geometry_msgs.msg import Point
from nav_msgs.msg import OccupancyGrid

import rosTiled


def main():
    proc= MapSubscriber()
    proc.run()

class MapSubscriber( rosTiled.Process ):

    # infinite loop
    def incommingMap(self, rosGridmapMsg):
        self.rosLogInfo("new GridMap ")
        self.rosOccupGrid_to_scene(rosGridmapMsg, 1.2)
        self.drawScene()
        
        self.setTileMarkerHeader( rosGridmapMsg.header )
        for tile in self._scene.tiles() :
            self.markeTile( tile )
        
        self.setGraphMarkerHeader( rosGridmapMsg.header )
        self.markeSceneGraph()

        return self

    def run(self):
        self.rosInit(f"tiled_map_subscriber")

        # Events handling :
        self.activateMarkerPublisher('tiledmap_marker')
        self.subscribeToGridMap("map", self.incommingMap )

        self.rosSpin()

if __name__ == '__main__':
    main()